<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="F_Messages" Id="{ff8464c9-d904-4617-be35-eb0c8e685418}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Messages : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;
{text'hello world'}
{info'information'}
{warn'warning'}
//{error'Error!'}]]></ST>
    </Implementation>
    <LineIds Name="F_Messages">
      <LineId Id="3" Count="3" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>